### ISSUE TITLE
BibTeX file for vignette references

### ISSUE THREAD

**Issue by corybrunson** [rrrlw/ggtda#28]
The vignettes include a great deal of front matter, the vast majority of it bibliographic. To make reading and editing the source code easier, would it make sense to maintain a single BibTeX (`.bib`) file with all references, which can then be cited in the vignettes? I haven't done this before so it may incur new issues, but i'd be glad to give it a try on a new branch. My point of reference is [this chapter in the _R Markdown Cookbook_](https://bookdown.org/yihui/rmarkdown-cookbook/bibliography.html).

**Comment by rrrlw** [comment]
That sounds good to me! Would you like me to switch it to bibtex?

**Comment by corybrunson** [comment]
@rrrlw go for it if you're up for it!

**Comment by rrrlw** [comment]
fixed in #31
