### ISSUE TITLE
drop theme_tda

### ISSUE THREAD

**Issue by corybrunson** [rrrlw/ggtda#35]
While reviewing the exported objects, i noticed that `theme_persist()` is a copy of `theme_tda()`. Since there will eventually be many more plot layers, some of which may be better suited to theme elements different from those of persistence diagrams, i would suggest dropping the generically-named `theme_tda()` in favor of defining only more precise themes as needed.

If agreed to, it would be good to do this as part of #21, to avoid future deprecation.

**Comment by rrrlw** [comment]
Agreed, I will drop `theme_tda` and tag you when PR is ready for review

**Comment by rrrlw** [comment]
fixed in #37
