### ISSUE TITLE
R 3.6.2 messes up stat_disk drawing

### ISSUE THREAD

**Issue by rrrlw** [rrrlw/ggtda#7]
Hey @corybrunson, just updated R to 3.6.2 and using stat_disk results in improperly rendered circles (below is example from ggtda GitHub README); possible that this is because of how circles are rendered as polygons instead? (geom_point from ggplot2 seems to be working okay)

![image](https://user-images.githubusercontent.com/6846515/71324453-bb165800-24ac-11ea-9069-541d4c5e4b27.png)

**Comment by corybrunson** [comment]
@rrrlw i've reproduced the error on my machine (which has Rv3.6.1 installed). It looks to me like a problem with the ordering of the vertices along the circle boundaries. I'll take a close look later today. Good catch.

**Comment by corybrunson** [comment]
@rrrlw see if installing (or `load_all()`ing) the `testing` branch resolves the issue for you. If so, feel free to merge into the main branch. : ) Might have been due to a change in the behavior of `tidyr::crossing()`; `tidyr::expand_grid()` has the needed effect without reordering the rows.

**Comment by rrrlw** [comment]
Somehow I closed the issue w/o intending to, maybe automatically when I merged the testing branch into master?

Either way...wow that was a super quick and effective solution, thanks a lot @corybrunson! Also thank you to @eashwarsoma for noticing the bug!
